version: '3'
services:
 api:
  build: .
  ports:
   - "3000:3000"
  links:
   - mongo
 mongoexpress:
  image: mongo-express
  ports: 
   - "28081:8081"
  links:
   - mongo
 mongo:
  image: mongo
  ports:
   - "27017:27017"
